/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RyansCursors {
        "joinRoom": (roomName: string) => Promise<void>;
        "leaveRoom": () => Promise<void>;
        "setMessage": (message: string) => Promise<void>;
    }
}
declare global {
    interface HTMLRyansCursorsElement extends Components.RyansCursors, HTMLStencilElement {
    }
    var HTMLRyansCursorsElement: {
        prototype: HTMLRyansCursorsElement;
        new (): HTMLRyansCursorsElement;
    };
    interface HTMLElementTagNameMap {
        "ryans-cursors": HTMLRyansCursorsElement;
    }
}
declare namespace LocalJSX {
    interface RyansCursors {
    }
    interface IntrinsicElements {
        "ryans-cursors": RyansCursors;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ryans-cursors": LocalJSX.RyansCursors & JSXBase.HTMLAttributes<HTMLRyansCursorsElement>;
        }
    }
}
